export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_SIGNUP_CHANGE = 'HANDLE_SIGNUP_CHANGE'
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE'

export const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT'

export const SET_USER = 'SET_USER'
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE'
export const FIND_USER = 'FIND_USER'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

//SEARCH
export const HANDLE_SEARCH = 'HANDLE_SEARCH'
export const FILTER_USERS = 'FILTER_USERS'

//PRIVATE-CHAT
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_PRIVATE_ROOM = 'SET_PRIVATE_ROOM'
export const REMOVE_USER = 'REMOVE_USER'
export const CONNECT_USER = 'CONNECT_USER'

export const OPEN_CHAT = 'OPEN_CHAT'
export const HANDLE_TAB_CHANGE = 'HANDLE_TAB_CHANGE'
export const CHANGE_CHAT = 'CHANGE_CHAT'
export const HANDLE_MESSAGE_INPUT_CHANGE = 'HANDLE_MESSAGE_INPUT_CHANGE'
export const ADD_PRIVATE_MESSAGE = 'ADD_PRIVATE_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_ROOMS = 'GET_ROOMS'
export const CHANGE_TAB_VALUE = 'CHANGE_TAB_VALUE'

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
export const REMOVE_SOCKET = 'REMOVE_SOCKET'
export const ADD_SOCKET = 'ADD_SOCKET'

export const GET_PRIVATE_ROOMS= 'GET_PRIVATE_ROOMS'
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const OPEN_ROOM = 'OPEN_ROOM'
