export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_SIGNUP_CHANGE = 'HANDLE_SIGNUP_CHANGE'
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE'

export const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT'

export const SET_USER = 'SET_USER'
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE'
export const FIND_USER = 'FIND_USER'





