export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_SIGNUP_CHANGE = 'HANDLE_SIGNUP_CHANGE'
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE'

export const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT'

export const SET_USER = 'SET_USER'
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE'
export const FIND_USER = 'FIND_USER'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

//SEARCH
export const HANDLE_SEARCH = 'HANDLE_SEARCH'
export const FILTER_USERS = 'FILTER_USERS'

//PRIVATE-CHAT
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_PRIVATE_ROOM = 'SET_PRIVATE_ROOM'












